# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.
# Please make changes to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "ahci"
        "nvme"
        "usbhid"
        "ums_realtek"
        "uas"
        "sd_mod"
      ];
      kernelModules = [ "dm-snapshot" ];

      luks.devices."cryptroot" = {
        device = "/dev/disk/by-uuid/1f46beca-dc9a-481b-86fe-275a697e3dc2";
        preLVM = true;
        # --- ADDED: Allow unlocking with FIDO2 (YubiKey) ---
        crypttabExtraOpts = [ "fido2-device=auto" ];
      };

      services.lvm.enable = true;
    };

    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/vg0-root";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/D223-DA20";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };

    "/var" = {
      device = "/dev/mapper/vg0-var";
      fsType = "ext4";
    };

    "/home" = {
      device = "/dev/mapper/vg0-home";
      fsType = "btrfs";
    };

    "/nix" = {
      device = "/dev/mapper/vg0-nix";
      fsType = "btrfs";
    };

    "/images" = {
      device = "/dev/mapper/vg0-images";
      fsType = "ext4";
    };
  };

  swapDevices = [
    { device = "/dev/mapper/vg0-swap"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
